### ISSUE TITLE
[Joss Review] Update gitignore

### ISSUE THREAD

**Issue by AKuederle** [cadop/seg1d#2] opened 2020-06-29 19:48 UTC
The repository contains a couple of file that usually should not be tracked by git.

This includes:

- `./dist` folder
- `*.egg` file
- `./docs/build`

 These files should be removed and added to the gitignore file.

More information on how to do this can be found here: https://www.git-tower.com/learn/git/faq/ignore-tracked-files-in-git

**Comment by cadop** [comment] 2020-06-30 00:33
Hi @AKuederle , thanks for reviewing. I removed the files for dist and egg, and added them to git ignore: https://github.com/cadop/seg1d/commit/4381eea8a7347feb5f06d417682aa86a74be278b 

However, I can't remove the docs/build because this is the folder github is using to generate the website (its one of three options): https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

**Comment by AKuederle** [comment] 2020-06-30 08:16
Ah I see :) this is indeed not possible in this case. Maybe you could think
about publishing the docs via readthedocs in the future? Definitely nothing
that should block this review of course.

Feel free to close the issue :)

**Comment by cadop** [comment] 2020-06-30 12:29
I will revisit the option for make a separate branch if the issue is about pulling the documentation. It is just difficult to maintain for me when I did it before.  Ill close this one, but just make a new issue for myself.

**Closed as completed by cadop** 2020-06-30 12:29 UTC
